# This is a basic workflow to help you get started with Actions

name: frontend code eslint

on:
  push:
    branches: [ V3.6.X**, release* ]
  pull_request:
    branches: [ V3.6.X**, release* ]

jobs:
  eslint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Install dependencies
        run: |
              cd frontend/desktop/
              npm install

      - name: Run Eslint
        run: |
              cd frontend/desktop/
              npx eslint --ext .js,.vue src/
