# release.yml

changelog:
  exclude:
    labels:
      - ignore-for-release-notes
  categories:
    - title: Breaking Changes ğŸ› 
      labels:
        - breaking-change
    - title: Exciting New Features ğŸ‰
      labels:
        - type/feature
    - title: Fixed Bugs ğŸ›
      labels:
        - type/bug
    - title: Optimizations âš™ï¸
      labels:
        - type/optimization 
    - title: Other Changes
      labels:
        - "*"
